name: CI/CD

on:
  push:
    branches:    
    - main

jobs:
  ci:
    name: CI/CD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Get poetry
        run: |
          pip install poetry==1.1.5
      - name: install project dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Check code formatting
        run: |
          black --check ./sspdata/ --exclude __init__.py --verbose
      - name: Check import orders
        run: |
          isort --check ./sspdata/ --skip __init__.py --gitignore --dont-follow-links --verbose
      - name: Linter
        run: |
          pylama ./sspdata/ ./tests/
      - name: Run tests
        run: |
          pytest ./tests/ --verbose --color=yes --code-highlight=yes
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.6
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
          poetry_version: '==1.1.6'
          repository_name: 'sspdata'
